config/routes.rb
Rails.application.routes.draw do
  root "albums#index"

  devise_for :users
  resources :albums do
    resources :photos, only: [:index, :new, :create] do 
      member do 
        delete :destroy_image
      end
    end
  end
 
  get "up" => "rails/health#show", as: :rails_health_check


end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :tags, dependent: :destroy
  has_many :photos, dependent: :destroy

  validates :title,presence: true
  validates :description,presence: true

  accepts_nested_attributes_for :tags,  allow_destroy: true
  scope :search, ->(query){
   return all if query.blank?
   left_joins(:tags).where("albums.title ILIKE :q OR tags.name ILIKE :q", q: "%#{query}%").distinct
  }

  def tags_attributes=(attributes)
    attributes.each do |i, tag_attribute|
      if tag_attribute[:_destroy] == "1"
        tag = self.tags.find_by(id: tag_attribute[:id])
        self.tags.delete(tag) if tag
        next
      end

      name = tag_attribute[:name].to_s.strip.downcase
      next if name.blank?
      tag = Tag.find_or_create_by(name: name)
      self.tags << tag unless self.tags.include?(tag)
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :album
  has_many_attached :images
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_and_belongs_to_many :albums, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :albums, dependent: :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_album, only: [:show, :update, :edit, :destroy]

  def index
    @query = params[:query]
    @albums = current_user.albums.search(@query)
  end

  def new
    @album = current_user.albums.new
  end

  def show
  end

  def update
    if @album.update(album_params)
      redirect_to albums_path, notice: "Album updated successfully"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def create
    @album = current_user.albums.new(album_params)    
    if @album.save
      redirect_to albums_path, notice: "Album created successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def destroy
    if @album.destroy
      redirect_to albums_path, notice:"Album deleted successfully"
    end
  end

  private

  def set_album
    @album = current_user.albums.find(params[:id])
  end

  def album_params
    params.require(:album).permit(:title, :description, tags_attributes: [:id, :name, :_destroy])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes

  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  def configure_permitted_parameters
    # For sign up
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # For account update
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_up_path_for(resource)
    albums_path
  end

  def after_sign_in_path_for(resource)
    albums_path
  end

  def after_sign_out_path_for(resource_or_scope)
    new_user_session_path
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :authenticate_user!
  before_action :set_album
 
  def index
    @photos = @album.photos
  end

  def new
    @photo=@album.photos.build
  end

  def create
    @photo=@album.photos.build(photo_params)

    if @photo.save
      redirect_to album_photos_path(@album),notice: "Photos uploaded successfully"
    else
      render :new, status: :unprocessable_entity
    end
  end
  
  def destroy_image
    photo=@album.photos.find(params[:id])
    image=photo.images.find(params[:image_id])
    image.purge

    redirect_back fallback_location: album_photos_path(@album)
  end

  private

  def set_album
    @album=current_user.albums.find(params[:album_id])
  end

  def photo_params
    params.require(:photo).permit(:title,images:[])
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/new_helper.rb
module NewHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/albums/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Albums#create</h1>
  <p>Find me in app/views/albums/create.html.erb</p>
</div>

app/views/albums/destroy.html.erb
<div>
  <h1 class="font-bold text-4xl">Albums#destroy</h1>
  <p>Find me in app/views/albums/destroy.html.erb</p>
</div>

app/views/albums/edit.html.erb
<div class="max-w-xl mx-auto bg-white p-6 rounded-base border border-gray-200 rounded-lg shadow-md">
  <h1 class="text-2xl font-semibold mb-6">Update Album</h1>

  <%= form_with model: @album, data: { turbo: false } do |f| %>

    <% if @album.errors.any? %>
      <div class="mb-4 bg-red-100 text-red-700 p-4 rounded">
        <ul>
          <% @album.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-4">
      <%= f.label :title, class: "block mb-1 font-medium" %>
      <%= f.text_field :title,
            class: "w-full border border-gray-300 rounded px-3 py-2",
            placeholder: "Album title" %>
    </div>

    <div class="mb-6">
      <%= f.label :description, class: "block mb-1 font-medium" %>
      <%= f.text_area :description,
            rows: 3,
            class: "w-full border border-gray-300 rounded px-3 py-2",
            placeholder: "Album description" %>
    </div>
    
    
  <div class="mb-4">
  <label class="block mb-1 font-medium">Tags</label>

  <input
    type="text"
    id="tag-input"
    placeholder="Tags..."
    class="w-full border border-gray-300 rounded px-3 py-2"
  >

  <!-- Visible tags -->
  <div id="tag-list" class="mt-2 flex gap-2 flex-wrap">
    <% if @album.persisted? %>
      <% @album.tags.each_with_index do |tag, index| %>
        <div
          class="inline-flex items-center gap-2 bg-gray-700 text-white px-3 py-1 rounded-full text-sm"
          data-index="<%= index %>"
        >
          <span><%= tag.name %></span>

          <button
            type="button"
            class="text-white/80 hover:text-white font-bold leading-none"
            onclick="removeExistingTag(<%= index %>)"
          >
            &times;
          </button>
        </div>
      <% end %>
    <% end %>
  </div>

  <!-- Hidden inputs -->
  <div id="hidden-tags">
    <% if @album.persisted? %>
      <% @album.tags.each_with_index do |tag, index| %>
        <input
          type="hidden"
          name="album[tags_attributes][<%= index %>][id]"
          value="<%= tag.id %>">

        <input
          type="hidden"
          id="destroy-tag-<%= index %>"
          name="album[tags_attributes][<%= index %>][_destroy]"
          value="0">
      <% end %>
    <% end %>
  </div>
</div>


    <div class="flex justify-end gap-3">
      <%= link_to "Cancel",
            albums_path,
            class: "text-gray-600 hover:underline" %>

      <%= f.submit "Update Album",
            class: "bg-indigo-600 hover:bg-indigo-700 text-white px-5 py-2 rounded" %>
    </div>

  <% end %>
</div>

app/views/albums/index.html.erb
<%= render "shared/navSidebar" %>
<div class="border-b">
  <div class="flex flex-col md:flex-row md:items-center md:justify-between px-4 ">
      <h1 class="font-semibold text-4xl py-4 sm:ml-64">
        Dashboard
      </h1>

      <!-- Search -->
      <div class="w-full mt-2 sm:mt-0 sm:ml-auto sm:mr-6 sm:w-96">
        <%= form_with url: albums_path, method: :get, local: true do %>
          <div class="flex gap-2">
            <%= text_field_tag :query,
              nil,
              placeholder: "Search",
              autocomplete: "off",
              class: "w-full px-4 py-2 rounded-lg
                   bg-white/10 placeholder-gray-400
                   border border-white/10
                   focus:outline-none focus:ring-2 focus:ring-indigo-500" %>

            <%= submit_tag "Search",
              class: "px-4 py-2 rounded-lg bg-indigo-600 text-white font-medium
                   hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500" %>
          </div>
        <% end %>
      </div>

  </div>
</div>


<div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-6 mt-5 mx-6 p-3 sm:ml-64 mt-14">
  <% @albums.each do |album| %>
    <div class="bg-neutral-primary-soft block max-w-sm p-6 border border-default rounded-base shadow-xs relative">

     <!-- Three dots menu -->
      <div class="absolute top-3 right-3">
        <button
          type="button"
          class="album-menu-btn w-8 h-8 flex items-center justify-center rounded-full hover:bg-gray-200 border border-gray-200"
        >
          <!-- three dots icon -->
          <svg class="w-5 h-5 text-gray-700" viewBox="0 0 24 24" fill="currentColor">
            <circle cy="5" cx="12" r="2" />
            <circle cy="12" cx="12" r="2" />
            <circle cy="19" cx="12" r="2" />
          </svg>
        </button>

        <!-- Dropdown -->
        <div class="album-menu hidden absolute right-0 mt-2 w-32 bg-white border border-gray-200 rounded shadow-lg z-50">
          <ul class="py-1 text-sm">
            <li>
              <%= link_to edit_album_path(album),
                class: "block px-4 py-2 hover:bg-gray-100" do %>
                Edit
              <% end %>
            </li>

            <li>
              <%= button_to album_path(album),
                method: :delete,
                data: { turbo_confirm: "Are you sure?" },
                class: "block w-full text-left px-4 py-2 text-red-600 hover:bg-gray-100 bg-transparent border-none cursor-pointer" do %>
                Delete
              <% end %>
            </li>
          </ul>
        </div>
        </div>

      <!-- Album Cover Image -->
      <% first_photo_with_image = album.photos.find { |photo| photo.images.attached? } %>
      <% if first_photo_with_image %>
        <%= image_tag first_photo_with_image.images.first, class: "rounded-base w-full h-48 object-cover" %>
      <% else %>
          <div class="w-full h-48 bg-gray-200 rounded-base flex items-center justify-center text-gray-500">
             No Image
          </div>
      <% end %>
      
      <!-- Album Title -->
        <h5 class="mt-6 mb-2 text-2xl text-blue-900 font-semibold tracking-tight text-heading">
          <%= album.title %>
        </h5>

      <!-- Album Description -->
      <p class="mb-6 text-body text-blue-900">
        <%= truncate(album.description, length: 100) %>
      </p>
      
      <!-- Tags -->
      <% if album.tags.any? %>
        <div class="mt-3 flex flex-wrap gap-2">
           <% album.tags.each do |tag|%>
              <span class="bg-gray-500 text-white text-xs px-3 py-1 rounded-full">
                <%= tag.name %>
              </span>
            <% end %>
        </div>
      <% end %>

      <!-- View Album Button -->
      <%= link_to album_photos_path(album),class: "mt-4 inline-flex items-center text-body bg-neutral-secondary-medium box-border border border-default-medium hover:bg-neutral-tertiary-medium hover:text-heading focus:ring-4 focus:ring-neutral-tertiary shadow-xs font-medium leading-5 rounded-base text-sm px-4 py-2.5 rounded focus:outline-none hover:bg-blue-500 hover:text-white" do %>
        View Album
        <svg class="w-4 h-4 ms-1.5 rtl:rotate-180 -me-0.5"
             xmlns="http://www.w3.org/2000/svg"
             fill="none" viewBox="0 0 24 24">
          <path stroke="currentColor" stroke-linecap="round"
                stroke-linejoin="round" stroke-width="2"
                d="M19 12H5m14 0-4 4m4-4-4-4" />
        </svg>
      <% end %>
    </div>
  <% end %>
 </div>

app/views/albums/new.html.erb
<div class="max-w-xl mx-auto bg-white p-6 rounded-base bg-white p-6 border border-gray-200 rounded-lg shadow-md">
  <h1 class="text-2xl font-semibold mb-6 text-gray-900 ">Create New Album</h1>

  <%= form_with model: @album, data: { turbo: false } do |f| %>

    <% if @album.errors.any? %>
      <div class="mb-4 bg-red-100 text-red-700 p-4 rounded">
        <ul>
          <% @album.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-4">
      <%= f.label :title, class: "block mb-1 font-medium " %>
      <%= f.text_field :title,
            class: "w-full border border-gray-300 rounded px-3 py-2",
            placeholder: "Album title" %>
    </div>

    <div class="mb-4">
      <%= f.label :description, class: "block mb-1 font-medium" %>
      <%= f.text_area :description,
            rows: 3,
            class: "w-full border border-gray-300 rounded px-3 py-2",
            placeholder: "Album description" %>
    </div>
    
    
    <div class="mb-4">
      <label class= "block mb-1 font-medium">Tags</label>

      <input
        type="text"
        id="tag-input"
        placeholder="Tags..."
        class="w-full border border-gray-300 rounded px-3 py-2"
      >
       
      <div id="tag-list" class="mt-2 flex gap-2 flex-wrap"></div>

      <div id="hidden-tags"></div>
    </div>

    <div class="flex justify-end gap-3">
      <%= link_to "Cancel",
            albums_path,
            class: "text-gray-600 hover:underline py-2" %>

      <%= f.submit "Create Album",
            class: "bg-indigo-600 hover:bg-indigo-700 text-white px-5 py-2 rounded" %>
    </div>

  <% end %>
</div>

app/views/albums/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Albums#show</h1>
  <p>Find me in app/views/albums/show.html.erb</p>
</div>

app/views/albums/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Albums#update</h1>
  <p>Find me in app/views/albums/update.html.erb</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Gallery" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Gallery">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
     <link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.4.1/flowbite.min.css"rel="stylesheet"/>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <main class="container mx-auto px-4 mt-8">
      <%= yield %>
    </main>
     <script src="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.4.1/flowbite.min.js"></script>
  </body>
</html>

app/views/photos/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Photo#create</h1>
  <p>Find me in app/views/photo/create.html.erb</p>
</div>

app/views/photos/index.html.erb
<%= render "shared/header" %>
<div class="flex justify-between items-center mb-6 p-4 mt-20 border-b">
  <h1 class="font-semibold text-4xl"><%= @album.title %></h1>

  <%= link_to "Upload Image",
        new_album_photo_path(@album),
        class: "bg-indigo-600 hover:bg-indigo-700 text-white px-5 py-2 rounded shadow-sm text-sm font-medium" %>
</div>

<!-- Images Grid -->
<% if @photos.any? %>
  <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-4 gap-6">
   <% @photos.each do |photo| %>
  <% if photo.images.attached? %>
    
      <% photo.images.each do |image| %>
        <div class="relative w-78 h-78 border border-blue-300 rounded overflow-hidden">

          <%= image_tag image,
                class: "h-full w-full object-cover rounded preview-image",data: { image_url: url_for(image) }  %>

          <%= link_to destroy_image_album_photo_path(photo.album, photo, image_id: image.id),
              data: { turbo_method: :delete, turbo_confirm: "Delete this image?" },
              class: "absolute top-2 right-2 bg-black/60 text-white rounded-full w-6 h-6 flex items-center justify-center text-sm hover:bg-red-600" do %>
            ✕
          <% end %>

        </div>
      <% end %>
  
  <% end %>
<% end %>

  </div>
<% else %>
  
  <div class="text-center py-20 text-gray-500">
    <p>No images uploaded yet.</p>
    <p class="text-sm">Click “Upload Image” to add your first photo.</p>
  </div>
<% end %>

<!-- Image Preview Modal -->
<div
  id="image-modal"
  class="fixed inset-0 bg-black/80 hidden items-center justify-center z-50"
>
  <!-- Close button -->
  <button
    id="close-modal"
    class="absolute top-4 right-6 text-white text-4xl font-bold hover:text-red-400"
  >
    &times;
  </button>

  <!-- Image -->
  <img
    id="modal-image"
    src=""
    class="max-h-[90vh] max-w-[90vw] object-contain rounded-lg shadow-xl"
  />
</div>

app/views/photos/new.html.erb
<div class="max-w-lg mx-auto bg-white p-6 rounded  border border-gray-200 rounded-lg shadow-md">
  <h2 class="text-xl font-semibold mb-4">Upload Image</h2>

  <%= form_with model: [@album, @photo], data: { turbo: false } do |f| %>

    <% if @photo.errors.any? %>
      <div class="mb-4 bg-red-100 text-red-700 p-3 rounded">
        <ul>
          <% @photo.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="mb-6">
      <%= f.label :image, class: "block mb-1 font-medium" %>
      <%= f.file_field :images,multiple: true,
            class: "w-full border px-3 py-2 rounded" %>
    </div>

    <div class="flex justify-end gap-3">
      <%= link_to "Cancel",
            album_photos_path(@album),
            class: "text-gray-600" %>

      <%= f.submit "Upload",
            class: "bg-indigo-600 hover:bg-indigo-700 text-white px-4 py-2 rounded" %>
    </div>

  <% end %>
</div>

app/views/shared/_header.html.erb
<nav class="fixed top-0 left-0 z-40 w-full h-16 bg-white border-b border-default shadow-md">
      <div class="flex items-center justify-between h-full px-6 gap-6">
       <%= link_to root_path, class: "flex items-center ps-2.5 gap-2" do %>
      <i class="fa-solid fa-images text-blue-500 text-2xl"></i>
      <span class="self-center text-xl text-heading font-bold whitespace-nowrap text-blue-900 py-4 font-bold">GalleryPro</span>
    <% end %>
        <% if current_user %>
           <div class="flex items-center justify-center gap-2">
    <span class=" font-bold text-lg text-blue-900 mt-4 mr-4 hidden md:inline">Hi, <%= current_user.name %>!</span>
    <%= button_to "Logout",
        destroy_user_session_path,
        method: :delete,
        data: { turbo: false },
        class: "bg-red-500 text-white rounded-lg px-4 py-2 hover:text-white transition" %>
    </div>
        <% else %>
          <%= link_to "Login",
              new_user_session_path,
              class: "bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-lg font-medium" %>
        <% end %>
      </div>
    </nav>

app/views/shared/_navSidebar.html.erb
<nav class="fixed top-0 left-0 z-40 w-full h-16 bg-white border-b border-default shadow-md">
  <div class="flex items-center justify-between h-full px-6">

    <!-- LEFT side -->
    <div class="flex items-center gap-4">
       
      <button
        id="sidebar-toggle"
        class="md:hidden text-2xl text-indigo-600 focus:outline-none">
        <i class="fa-solid fa-bars"></i>
      </button>

      <!-- Logo -->
      <%= link_to root_path, class: "md:hidden flex items-center gap-2" do %>
        <i class="fa-solid fa-images text-blue-500 text-2xl"></i>
        <span class="text-xl font-bold text-blue-900 whitespace-nowrap">
          GalleryPro
        </span>
      <% end %>
    </div>

    <!-- RIGHT side -->
    <div class="flex items-center gap-6">
      <% if current_user %>
        <span class="hidden md:inline font-bold text-lg text-blue-900">
          Hi, <%= current_user.name %>!
        </span>

        <%= button_to "Logout",
          destroy_user_session_path,
          method: :delete,
          data: { turbo: false },
          class: " bg-red-500 text-white rounded-lg px-4 py-2 hover:bg-red-600 transition" %>
      <% else %>
        <%= link_to "Login",
          new_user_session_path,
          class: "bg-blue-500 hover:bg-blue-600 text-white px-4 py-2 rounded-lg font-medium" %>
      <% end %>
    </div>

  </div>
</nav>


<aside id="top-bar-sidebar" class="fixed top-0 left-0 z-50 w-64 h-full transition-transform -translate-x-full sm:translate-x-0 bg-blue-900 text-white" aria-label="Sidebar">
 <!-- Mobile close button -->
  <div class="flex items-center justify-end sm:hidden px-4 py-3">
    <button
      id="sidebar-close"
      class="text-2xl text-white focus:outline-none">
      <i class="fa-solid fa-xmark"></i>
    </button>
  </div>   

  <div class="relative z-10 h-full px-4 py-4 overflow-y-auto border-e border-blue-700">
    <%= link_to root_path, class: "flex items-center ps-2.5 mb-5 gap-2" do %>
      <i class="fa-solid fa-images text-blue-500 text-2xl"></i>
      <span class="self-center text-xl text-heading font-bold whitespace-nowrap text-white font-bold">GalleryPro</span>
    <% end %>

    <ul class="mt-10 font-medium ">
      <li>
      <%= link_to albums_path,class: "flex items-center gap-3 px-3 py-3 text-white rounded-base hover:bg-blue-800/60 transition" do %>
        <i class="fa-solid fa-house w-5 text-center"></i>
        <span>Dashboard</span>
      <% end %>
      </li>
      
      <li>
      <%= link_to new_album_path,class: "flex items-center gap-3 px-3 py-3 text-white rounded-base hover:bg-blue-800/60 transition" do %>
        <i class="fa-solid fa-circle-plus w-5 text-center"></i>
        <span>Create Album</span>
      <% end %>
      </li>

     <li>
         <!-- Categories header -->
        <%= link_to "#",
            class: "flex items-center gap-3 px-3 py-3 text-white rounded-base
                    transition border-t border-white" do %>
          <i class="fa-solid fa-folder-open w-5 text-center"></i>
          <span class="font-medium">Categories</span>
        <% end %>

        <ul class="ml-16 flex flex-col gap-1">
          <% @albums.each do |album| %>
             <li>
                <%= link_to album_photos_path(album),
                  class: "flex items-center gap-4 px-3 py-2 rounded hover:bg-blue-700/50 transition text-white" do %>
               <i class="fa-solid fa-image w-4 text-center"></i>
               <span><%= album.title %></span>
               <% end %>
              </li>
          <% end %>
        </ul>

      </li>
      
    </ul>
  </div>
</aside>

 <!-- Main Content Wrapper -->
<div class="p-4 sm:ml-64 mt-14">
  <%= yield %>
</div>